# Generated by Django 6.0 on 2025-12-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ragliteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="model",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
